export const CREATE_REGISTER = "CREATE_REGISTER";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const ALL_CUSTOMER_DATA = "ALL_CUSTOMER_DATA";
export const ALL_ADMIN_DATA = 'ALL_ADMIN_DATA';
export const GET_SINGLE_CUSTOMER = "GET_SINGLE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";